### PR TITLE
add Section to make access to learning material and coaches introduction easier

### PR DESCRIPTION
**Pull request by gnunicorn**
as said before....

this way, it is really great to use the python.opentechschool.org as the starting point for any workshop we are hosting (aka just telling the learners to go there)

### CODE REVIEW

**Comment by gnunicorn** [comment]
@lehmannro may you be so kind and review my work?

**Comment by lehmannro** [comment]
Sounds good, a couple of minor points:
- Capitalization of words should be uniform, ie. "workshop" (instead of
  "Workshop"), "mailing list" (instead of "Mailing list.")
- The "Learning Materials" section could just jump down the page to the
  longer description.  (Is there something like an auto-generated TOC?)
- The Django material is in the TOC, but lacks a longer description.
- Not sure if the Twitter workshop should be left completely unmentioned.
- Do col_left/col_right need to be defined twice, in styles.css /and/
  style.css?

None of these are really blockers if you need this in before Monday.

On Sat, Jun 29, 2013 at 2:55 PM, Benjamin Kampmann <notifications@github.com

**Comment by gnunicorn** [comment]
Ok. Fixed the raised issues. 
- Added Sections about Facebook Client and Django
- removed old, not-used styles.css
- linked TOCs to inline
- copy edits

re Twitter: not sure what to do about it. Why would you want to mention it? Sure it was great but it also is defunct. If you want to have it for a reference for coaches, we can point them to the facebook client - it is basically a copy. Or you had anything else in mind?

**Comment by lehmannro** [comment]
LGTM, I'm fine with leaving the Twitter workshop out as long as it's
retained on the wiki.  (There is a typo left in the "Learning Materials"
TOC, where it should be "Data Processing in Python" instead of "... ih
Python.")

**Pull request merged**
